// /types/database.types.ts

// THIS FILE IS AUTO-GENERATED BY SUPABASE.
// DO NOT EDIT MANUALLY.

// Run the following command to generate this file:
// npx supabase gen types typescript --project-id YOUR_PROJECT_ID > types/database.types.ts

// It will look something like this once generated:
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      // Your table names will appear here, e.g., 'products'
      products: {
        Row: {
          id: number
          name: string
          // ... all your other columns
        }
        Insert: {
          // ... types for inserting new rows
        }
        Update: {
          // ... types for updating rows
        }
      }
    }
    Views: {
      // Your database views will appear here
    }
    Functions: {
      // Your database functions will appear here
    }
  }
}
